spring.application.name=Order-Service
server.port=8084

# H2 Database (In-memory)
spring.datasource.url=jdbc:h2:mem:orderdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

#Enabling h2-console and path
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.jpa.hibernate.ddl-auto=none
spring.sql.init.mode=always


logging.level.com.order.feignClient=DEBUG
logging.level.feign=DEBUG

eureka.client.service-url.defaultZone=http://localhost:8761/eureka

management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always


# Retry configuration for getProductById
resilience4j.retry.instances.getProductByIdRetry.max-attempts=5
resilience4j.retry.instances.getProductByIdRetry.wait-duration=2s
resilience4j.retry.instances.getProductByIdRetry.enable-exponential-backoff=true



# Retry configuration for reduceStockRetry
resilience4j.retry.instances.reduceStockRetry.max-attempts=5
resilience4j.retry.instances.reduceStockRetry.wait-duration=2s
resilience4j.retry.instances.reduceStockRetry.enable-exponential-backoff=true

#Zipkin Config
management.tracing.sampling.probability=1.0
management.zipkin.tracing.endpoint=http://localhost:9411/api/v2/spans


